# Generated by Django 5.0.4 on 2024-04-09 10:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('customer_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_password', models.CharField(max_length=128)),
                ('employee_address', models.CharField(max_length=250)),
                ('employee_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('employee_id_type', models.CharField(max_length=50)),
                ('employee_id_number', models.CharField(max_length=20)),
                ('employee_sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('product_number', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_sales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('received_amount', models.IntegerField()),
                ('return_amount', models.IntegerField()),
                ('customer_billed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('billing_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('sold_products', models.ManyToManyField(to='home.product')),
            ],
        ),
    ]
