# Generated by Django 5.0.4 on 2024-04-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_number',
            new_name='product_code',
        ),
    ]
