# Generated by Django 5.0.4 on 2024-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_password',
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$tRxPdtiBtwJ9jLQFo2yGHX$cNkAdfLiGAh7j7WQs25T/qXsk5HBn5WWPd3GxnIFr4E=', max_length=128),
        ),
    ]
