# Generated by Django 5.0.4 on 2024-04-09 15:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_employee_password_alter_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.EmailField(default='default@xyz.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
