# Generated by Django 5.0.4 on 2024-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_employee_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_email',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
